issue:
  outputs:
    dev:
      type: postgres
      threads: 2
      host: "{{ env_var('DBT_HOST') or 'localhost'}}"
      port: 5432
      user: postgres
      pass: password
      dbname: postgres
      schema: postgres
  target: dev
